CREATE TABLE `products` (
  `PRODUCT_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRICE` int NOT NULL DEFAULT '0',
  `STOCK` int NOT NULL DEFAULT '30',
  `INITIAL_STOCK` int NOT NULL DEFAULT '30',
  `IS_LIMITED` tinyint(1) NOT NULL DEFAULT '0',
  `IMAGE_PATH` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRODUCT_ID`),
  UNIQUE KEY `UQ_PRODUCTS_NAME` (`NAME`),
  CONSTRAINT `CK_PRODUCTS_STOCK` CHECK ((`STOCK` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `users` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAME` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PASSWORD_HASH` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UQ_USERS_EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `carts` (
  `CART_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `QUANTITY` int NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CART_ID`),
  UNIQUE KEY `UQ_CARTS_USER_PRODUCT` (`USER_ID`,`PRODUCT_ID`),
  KEY `IDX_CARTS_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_CARTS_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`),
  CONSTRAINT `FK_CARTS_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `CK_CARTS_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  `ORDER_ID` int NOT NULL AUTO_INCREMENT,
  `ORDER_NO` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_ID` int NOT NULL,
  `TOTAL_PRICE` int NOT NULL DEFAULT '0',
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PAYMENT_METHOD` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CARD',
  `PAYMENT_STATUS` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `FAIL_REASON` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SERVER_ENV` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORDER_ID`),
  UNIQUE KEY `UQ_ORDERS_ORDER_NO` (`ORDER_NO`),
  KEY `IDX_ORDERS_USER_CREATED` (`USER_ID`,`CREATED_AT`),
  KEY `IDX_ORDERS_ENV_STATUS` (`SERVER_ENV`,`STATUS`),
  CONSTRAINT `FK_ORDERS_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `CK_ORDERS_PAYMENT_STATUS` CHECK ((`PAYMENT_STATUS` in ('APPROVED','FAILED'))),
  CONSTRAINT `CK_ORDERS_SERVER_ENV` CHECK ((`SERVER_ENV` in ('aws','onprem'))),
  CONSTRAINT `CK_ORDERS_STATUS` CHECK ((`STATUS` in ('SUCCESS','FAIL')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_items` (
  `ORDER_ITEM_ID` int NOT NULL AUTO_INCREMENT,
  `ORDER_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `QUANTITY` int NOT NULL,
  `UNIT_PRICE` int NOT NULL,
  `SUBTOTAL` int NOT NULL,
  PRIMARY KEY (`ORDER_ITEM_ID`),
  KEY `IDX_ORDER_ITEMS_ORDER` (`ORDER_ID`),
  KEY `IDX_ORDER_ITEMS_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_ORDER_ITEMS_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`),
  CONSTRAINT `FK_ORDER_ITEMS_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`),
  CONSTRAINT `CK_ORDER_ITEMS_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
